---
- name: copy facts to managed hosts
  hosts: nodes

  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact

  tasks:
  - name: create remote directory
    file:
      state: directory
      recurse: yes
      path: "{{remote_dir}}"

  - name: install new facts
    copy: 
      src: "{{ facts_file }}"
      dest: "{{ remote_dir }}"


...
