---
- shell:
    rpm -q httpd
  register: rpm_check
  failed_when: rpm.check.rc == 1

- block:
  - get_url:
    url: "{{ https_uri }}"
    dest: /etc/httpd/conf.d

  - file:
      path: /etc/httpd/conf.d/ssl
      state: directory
      mode: 0755

  - template:
      src: https.j2
      dest: /etc/httpd/conf.d/ssl.conf
      owner: root
      group: root
      mode: 0755

  - unarchive:
      src: "{{ ssl_uri }}"
      dest: /etc/httpd/conf.d/ssl/
      copy: no
    notify:
      - restart_services

  - copy:
    content: "{{ ansible_fqdn }} ( {{ ansible_default_ipv4.address }} ) has been customized by Ansible\n"
    dest: /var/www/html/index.html

  when:
    rpm.check.rc == 0
