---
- name: intranet services
  hosts: ansible106.ecm.com, ansible107.ecm.com
  become: yes
  become_user: root

  tasks:
  - name: latest httpd version installed
    yum:
      name: httpd
      state: latest

  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: httpd enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled

  - name: restart firewalld
    service:
      name: firewalld
      state: restarted

