---

- name: deploy vsftpd
  hosts: ansible106.ecm.com, ansible107.ecm.com

  tasks:
    - name: install vsftpd
      package:
        name: vsftpd
        state: latest

    - name: enable vsftpd
      service:
        name: vsftpd
        enabled: true

    - name: create readme file
      copy:
        content: "Welcome to my friendly server\n"
        dest: /var/ftp/pub/README
        force: no
        mode: 0444

...
