---

# note: this solution is incomplete but gives a good impression of where to go

- name: deply and start Apache
  hosts: nodes

  
  tasks:
    - name: Include the OS-specific variables.
      include_vars: "./vars/{{ ansible_os_family }}.yml"

    - name: install and update the latest packages
      package:
        name:
          - "{{ packages.web_package }}"
          - "{{ packages.firewall_package }}"
          - "{{ packages.ftp_package }}"
          - "{{ packages.db_package }}"
        state: latest
      notify:
        - success

    - name: start and enable {{ services.firewall_service }}
      service:
        name: "{{ services.firewall_service }}"
        enabled: true
        state: started

    - name: start and enable {{ services.web_service }}
      service:
        name: "{{ packages.web_package }}"
        enabled: true
        state: started

    - include_tasks: tasks/ubuntu.yml
      when: ansible_os_family == 'Ubuntu'

    - include_tasks: tasks/redhat.yml
      when: ansible_os_family == 'RedHat'

  handlers:
    - name: success
      debug:
        msg: package installation on {{ inventory_hostname }} successful

    
