---

- name: download large file
  hosts: file

  tasks:
    - name: download large file
      get_url:
        url: https://mirrors.aliyun.com/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-Minimal-2009.iso
        dest: /tmp
      async: 7200
      poll: 0
      register: background_download

    - name: wait for download completion
      async_status:
        jid: "{{ background_download.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 50
      delay: 120
